local_web/BedTool/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from picture import urls as pic_urls
from picture.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('picture/',include((pic_urls,'picture'),namespace="picture")),
    re_path(r'^$',login)
]

local_web/picture/urls.py
from django.urls import path
from picture.views import login, index, upload_image,image_list,delete_img,edit_tag,delete_tag

urlpatterns = [
    path('login/', login, name="login"),
    path('index/', index, name="index"),
    path('upload_image/', upload_image, name="upload_image"),
    path('image_list/',image_list,name="image_list"),
    path('delete_img/',delete_img,name="delete_img"),
    path('edit_tag/',edit_tag,name="edit_tag"),
    path('delete_tag/',delete_tag,name="delete_tag")
]

local_web/picture/models.py
from django.db import models
import hashlib
from datetime import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class FileInfo(models.Model):

    """上传的文件信息"""
    id=models.AutoField(primary_key=True,verbose_name="序号")
    filename = models.CharField('文件名', max_length=128)
    md5_name = models.CharField('加密名称', max_length=64)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tags=models.CharField(verbose_name="标识",max_length=255,null=True,blank=True)
    upload_date = models.DateTimeField('上传时间', default=timezone.now)
    removed = models.IntegerField('已删除', default=0)

    # @classmethod
    # def create(cls, filename, user):
    #     file = cls(filename=filename, user=user)
    #     file.md5_name = cls._generate_md5_name(filename)
    #     return file
    #
    # @staticmethod
    # def _generate_md5_name(filename):
    #     """生成md5加密后的名称，加入当前时间字符串，避免文件名重复带来的问题"""
    #     md5_str = datetime.strftime(datetime.now(), "%Y-%m-%dT%H:%M:%S") + filename
    #     return hashlib.md5(md5_str.encode('utf-8')).hexdigest() + '.' + filename.split('.')[-1]

local_web/picture/views.py
from django.shortcuts import render
from picture.AccountForm import LoginForm
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.utils import timezone
# Create your views here.
import os, time, hashlib
from django.conf import settings
from picture.models import FileInfo
from aws_hepler import upload_aws_image,search_image_by_tag,delete_img_by_name,search_image_by_image,delete_tags_by_tag
#from pure_pagination import Paginator, PageNotAnInteger
from django.db.models import Q
import base64

def get_md5():
    time_now = timezone.now()
    m = hashlib.md5()
    m.update(str(time_now).encode())
    return m.hexdigest()


# 用户登录
def login(request):
    if request.method == "GET":
        login_form = LoginForm()
        return render(request, 'login.html', {"login_form": login_form})
    else:
        login_form = LoginForm(request.POST)
        status = False
        if login_form.is_valid():
            username = login_form.cleaned_data["username"]
            password = login_form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                status = True
                auth_login(request, user)
                return JsonResponse({"status": status})
            else:
                login_form.add_error("password", "密码错误")
        return JsonResponse({"res": login_form.errors.as_json(), "status": status})


# 首页
def index(request):
    return render(request, 'index.html')


import base64


def upload_image(request):
    if request.method == "POST":
        image = request.FILES.get('file')
        ext = os.path.splitext(image.name)[1]
        timestrap = time.strftime('%Y%m%d', time.gmtime())
        md5_pwd = get_md5()
        NewFileName = "%s$$%s%s" % (image.name, md5_pwd, ext)
        image_byte = image.read()
        image_base64 = str(base64.b64encode(image_byte))[2:]
        response = upload_aws_image(image.name, image_base64)

        request.session["bs"]=image_base64
        if response.status_code == 200:
            res = {
                "code": 0,
                "msg": 'Uploaded',
                "data": {
                    "src": "/" + os.path.join("static", "uploads", timestrap, NewFileName).replace("\\", "/"),
                    "name": image.name,
                    "base64":image_base64
                }
            }
        else:
            res = {
                "code": 400,
                "msg": 'Failed',
            }

        return JsonResponse(res)

    return render(request, 'upload_image.html')


def edit_tag(request):
    res = {"code": 200, "msg": "sucess"}
    try:
        id = request.POST.get("id")
        fileinfo = FileInfo.objects.get(id=id)
        tags = request.POST.get("tag")
        fileinfo.tags = tags
        fileinfo.save()
    except:
        res["code"] = 500
        res["msg"] = "Failed"
    return JsonResponse(res)
import json

def image_list(request):
    q = request.GET.get("q")
    name=request.GET.get('name')
   
    image_lists = []
    if name is not None  and name !=""  :
        res=search_image_by_image(name, request.session.get("bs"))

        body = json.loads(res["body"])
        if len(body):
            for item in body:
                if item['tags']:
                    tags = item["tags"]
                else:
                    tags = []
                image_lists.append({
                    "name":os.path.basename(item["id"]),
                    "tags":tags
                })
    else:
        tag_list=[]
        if q !="" and q is not None:
            tag_list.append(q)
        res=search_image_by_tag(tag_list)
        if res.status_code==200:

            links=json.loads(res.json()["body"])["links"]
            if len(links):
                for item in links:
                    if item['tags']:
                        tags=item["tags"]
                    else:
                        tags=[]
                    image_lists.append({
                        "name": os.path.basename(item["id"]),
                        "tags": tags
                    })

        else:
            pass

    if q is None:
        q=""


    return render(request, 'img_list.html', {"img_list": image_lists, "q": q})

#删除图像
def delete_img(request):
    res = {"code": 200, "msg": "sucess"}
    if request.method == "POST":
        try:
            imagename = request.POST.get("imagename")
            result=delete_img_by_name(imagename)
            if "errorMessage" in result:
                res["msg"] = "Delete failed"
                res["code"] = 500
                return JsonResponse(res)
            return JsonResponse(res)
        except:
            res["msg"] = "Delete failed"
            res["code"] = 500
            return JsonResponse(res)


def delete_tag(request):
    res={"code":200,"msg":"sucess"}
    name=request.POST.get("name")
    tag=request.POST.get("tag")
    result=delete_tags_by_tag(name,tag)

    return JsonResponse(res)

local_web/templates/img_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="/static/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <link rel="stylesheet" href="/static/css/plugins/sweetalert/sweetalert.css">
    <link rel="stylesheet" href="/static/css/baguetteBox.min.css">
    <link rel="stylesheet" href="/static/css/gallery-clean.css">
    <link rel="stylesheet" href="/static/style.css">
    <style>

        .jq22-demo {
            text-align: center;
            margin-top: 30px;
        }

        .jq22-demo a {
            padding-left: 20px;
            padding-right: 20px;
        }

        .tz-gallery .thumbnail {
            padding: 0;
            margin-bottom: 30px;
            border: 1px solid #ccc;
        }

        .thumbnail a > img, .thumbnail > img {
            margin-right: auto;
            margin-left: auto;
            height: 300px;
            width: 100%;
        }

        #title {
            font: bold 48pt "Trebuchet MS";
            text-align: center;
            color: #F95;
            letter-spacing: -2px;
        }

        #title span {
            font-weight: normal;
            color: #BBB;
        }

        .tags {
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            box-shadow: 1px 1px 4px #CCC inset;
            padding: 10px;
            width: 100%;
            background: #fafafa;
            margin: auto;
        }

        #tag-typer {
            outline: none;
            border: none;
            padding: 6px;
            margin: 3px;
            margin-right: -25px;
            width: 100px;
            background-color: transparent;
            font-size: 14px;
            color: #333;
        }

        .tag {

            display: inline-block;
            background: #F95;
            color: #FFF;
            padding: 5px 7px;
            margin: 1px -4px 2px 14px;
            font: normal 16px sans-serif;
            position: relative;
            cursor: default;
            box-shadow: 1px 1px 0 rgb(0 0 0 / 20%);
            -webkit-transform-origin: 0% 50%;
            -webkit-animation: swing 1s;
            -o-animation: swing 1s;
            animation: swing 1s;
            /* float: left; */
            font-size: 15px;

        }

        .tag:before {
            content: "";
            position: absolute;
            width: 0;
            background: inherit;
            height: 10px;
            border: 10px solid #fafafa;
            border-right-color: transparent;
            -webkit-border-radius: 10px 0 0 10px;
            -moz-border-radius: 10px 0 0 10px;
            border-radius: 10px 0 0 10px;
            left: -20px;
            top: 0;
        }

        .tag:after {
            content: "";
            width: 6px;
            height: 6px;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
            border-radius: 3px;
            background: #FFF;
            position: absolute;
            left: -3px;
            top: 12px;
            box-shadow: inset 1px 1px 0 #CCC;
        }

        .tag .close {
            position: absolute;
            background: inherit;
            left: -4px;
            z-index: 3;
            visibility: hidden;
        }

        .tag:hover .close {
            visibility: visible;

        }

        .close:hover {
            color: rgba(0, 0, 0, .5);
        }


        .colors {
            list-style: none;
        }

        .colors li {
            display: inline-block;
            width: 15px;
            height: 15px;
        }

        /* Chrome, Safari, Opera */
        @-webkit-keyframes swing {
            0% {
                -webkit-transform: rotate(100deg)
            }
            25% {
                -webkit-transform: rotate(-25deg)
            }
            50% {
                -webkit-transform: rotate(15deg)
            }
            100% {
                -webkit-transform: rotate(0deg)
            }
        }


        @keyframes swing {
            0% {
                -webkit-transform: rotate(-200)
            }
            25% {
                -webkit-transform: rotate(-70)
            }
            50% {
                -webkit-transform: rotate(-185)
            }
            100% {
                -webkit-transform: rotate(-180)
            }
        }
    </style>
</head>
<body>
<div class="htmleaf-container">
    <div class=" gallery-container">
        <div class="tz-gallery">
            <div class="row" style="margin-bottom: 20px">
                <div class="col-md-12">
                    <form role="search" class="navbar-form-custom form-inline" method="get"
                          action="{% url 'picture:image_list' %}">
                        <div class="form-group">
                            <input type="text" placeholder="search" class="form-control" name="q"
                                   id="top-search" style="width:350px" value="{{ q }}">
                            <input type="submit" class="btn btn-primary" value="Search">
                        </div>
                        <a href="/picture/upload_image/" class="btn btn-primary" style="float: right;margin-right: 20px;">upload image</a>
                    </form>
                </div>
            </div>
            <div class="layui-card">
                <div class="layui-card-header">Search by image</div>
                <div class="layui-card-body">
                    <div class="layui-upload">
                        <div class="layui-upload-drag" id="uploadbtn" style="width: 94%">
                            <i class="layui-icon layui-icon-upload"></i>
                            <p>Drop Image Or click Upload</p>
                        </div>
                        <div class="layui-upload-list">
                            <img class="layui-upload-img" id="demo1">
                            <div id="tag" style="font-size: 18px;margin-top: 10px"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for item in img_list %}
                    <div class="col-sm-6 col-md-3" id="{{ item }}" style="height: 600px;">
                        <div class="thumbnail">
                            <a class="lightbox" href="https://fit5225ass.s3.amazonaws.com/images/{{ item.name }}">
                                <img src="https://fit5225ass.s3.amazonaws.com/images/{{ item.name }}" alt="Park">
                            </a>
                            <div class="caption">
                                <ul class="list-group">
                                    <li class="list-group-item "><label for="tag-typer">
                                        <div class="tags">
                                            {% for tag in item.tags %}
                                                <span class="tag" file="{{ item.name }}"><span
                                                        class="close">×</span>{{ tag }}</span>
                                            {% endfor %}
                                        </div>

                                    <li class="list-group-item"> name：{{ item.name }}</li>

                                </ul>
                                <button type="button" class="btn btn-danger delete" file="{{ item.name }}">delete</button>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>

    </div>

</div>
<script src="/static/js/jquery.min.js" charset="utf-8"></script>
<script type="text/javascript" src="/static/js/baguetteBox.min.js"></script>
<script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>


<script src="/static/layui/layui.js" charset="utf-8"></script>
<script src="/static/script.js"></script>
<script>
    layui.use('upload', function () {
        var upload = layui.upload;

        var uploadInst = upload.render({
            elem: '#uploadbtn'
            , url: "{% url 'picture:upload_image' %}"
            // , before: function (obj) {
            //     //预读本地文件示例，不支持ie8
            //     obj.preview(function (index, file, result) {
            //         $('#demo1').attr('src', result);
            //     });

            // }
            , done: function (res) {
                //这里回调函数的参数res就是接口返回的数据
                //alert(JSON.stringify(res.data.src))
                //如果上传失败
                window.location.href = '/picture/image_list/?name=' + res["data"]["name"] 
                if (res.code > 0) {
                    return layer.msg('upload faild');
                }
                layer.msg('Uploaded')


            }
            , error: function () {
                
                var demoText = $('#demoText');
                demoText.html('<span style="color: #FF5722;">Failed</span> <a class="layui-btn layui-btn-xs demo-reload">重试</a>');
                demoText.find('.demo-reload').on('click', function () {
                    uploadInst.upload();
                });
            }
        });
    })
</script>
<script>
    $(function () {
        $('.delete').click(function () {
            var imagename = $(this).attr("file");
            var that = this
            swal({
                title: "Do you want to delete it ",
                text: "",
                type: "warning",
                showCancelButton: true,
                cancelButtonText: 'Cancel',
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Delete",
                closeOnConfirm: false
            }, function () {
                $.post("{% url 'picture:delete_img' %}", {"imagename": imagename}, function (data) {
                    if (data["code"] = 200) {
                        swal(data["msg"], "Deleted", "success");
                        $(that).parent().parent().parent().remove()
                    } else {
                        swal("Done", data["msg"], "error");
                    }
                })
            });


        });
        
    })
</script>
<script type="text/javascript">
    baguetteBox.run('.tz-gallery');
</script>
</body>
</html>

local_web/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">

    <title>Tagtag</title>

    <meta name="keywords" content="">
    <meta name="description" content="">

    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->

    <link rel="shortcut icon" href="favicon.ico"> <link href="/static/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css?v=4.1.0" rel="stylesheet">
</head>

<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close"><i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-t-xs" style="font-size:20px;">
                                        <i class="fa fa-area-chart"></i>
                                        <strong class="font-bold">图床系统</strong>
                                    </span>
                                </span>
                            </a>
                        </div>
                        <div class="logo-element">图床系统</div>
                    </li>


                    <li class="line dk"></li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">分类</span>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-picture-o"></i> <span class="nav-label">相册</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="{% url 'picture:image_list' %}">相册列表</a>
                            </li>


                        </ul>
                    </li>


                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header"><a class="navbar-minimalize minimalize-styl-2 btn btn-info " href="#"><i class="fa fa-bars"></i> </a>

                    </div>

                </nav>
            </div>
            <div class="row J_mainContent" id="content-main">
                <iframe id="J_iframe" width="100%" height="100%" src="{% url 'picture:image_list'%}" frameborder="0" data-id="index_v1.html" seamless></iframe>
            </div>
        </div>
        <!--右侧部分结束-->
    </div>

    <!-- 全局js -->
    <script src="/static/js/jquery.min.js?v=2.1.4"></script>
    <script src="/static/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="/static/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/static/js/plugins/layer/layer.min.js"></script>

    <!-- 自定义js -->
    <script src="/static/js/hAdmin.js?v=4.1.0"></script>
    <script type="text/javascript" src="/static/js/index.js"></script>

    <!-- 第三方插件 -->
    <script src="js/plugins/pace/pace.min.js"></script>

</body>

</html>

local_web/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/layui/css/layui.css" media="all">
    <style>
        html, body {
            width: 100%;
            height: 100%;
            overflow: hidden
        }

        body {
            background: #1E9FFF;
            background-image: url("/static/img/bg.png");
            background-size: 100% 100%;
        }

        body:after {
            content: '';
            background-repeat: no-repeat;
            background-size: cover;
            -webkit-filter: blur(3px);
            -moz-filter: blur(3px);
            -o-filter: blur(3px);
            -ms-filter: blur(3px);
            filter: blur(3px);
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: -1;
        }

        .layui-container {
            width: 100%;
            height: 100%;
            overflow: hidden
        }

        .admin-login-background {
            width: 450px;
            height: 300px;
            border-radius: 3px;
            padding: 15px;
            position: absolute;
            left: 50%;
            top: 55%;
            transform: translate(-50%, -50%);
        }


        .logo-title {
            text-align: center;
            letter-spacing: 2px;
            padding: 14px 0;
        }

        .logo-title h1 {
            color: #1E9FFF;
            font-size: 25px;
            font-weight: bold;
        }

        .login-form {
            background-color: rgba(255, 255, 255, 0.0);
            border: 1px solid #fff;
            border-radius: 3px;
            padding: 14px 20px;
            box-shadow: 0 0 8px #eeeeee;
            padding-top: 100px
        }

        .login-form .layui-form-item {
            position: relative;
        }

        .login-form .layui-form-item label {
            position: absolute;
            left: 1px;
            top: 1px;
            width: 38px;
            line-height: 36px;
            text-align: center;
            color: #d2d2d2;
        }

        .login-form .layui-form-item input {
            padding-left: 36px;
        }

        .captcha {
            width: 60%;
            display: inline-block;
        }

        .captcha-img {
            display: inline-block;
            width: 34%;
            float: right;
        }

        .captcha-img img {
            height: 34px;
            border: 1px solid #e6e6e6;
            height: 36px;
            width: 100%;
        }

        .title {
            font-size: 80px;
            font-weight: 800;
            font-family: "Microsoft YaHei";
            text-align: center;
            color: whitesmoke;
            margin-top: 150px;
        }

        .avatar_box {
            height: 130px;
            width: 130px;
            border: 1px solid #eee;
            border-radius: 50%;
            padding: 10px;
            box-shadow: 0 0 10px #ddd;
            position: absolute;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: rgba(255, 255, 255, 1);
        }

        .avatar_box > img {
            width: 100%;
            height: 100%;
            border-radius: 50%;



        }
    </style>

</head>
<body>
<div class="layui-container">
    <div class="title">
        Tagtag
    </div>
    <div class="admin-login-background">
        <div class="avatar_box">
            <img src="/static/img/logo.jfif" alt=""/>
        </div>
        <div class="layui-form login-form">
            <form class="layui-form" action="">
                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-username" for="username"></label>
                    {{ login_form.username }}
                </div>


                <div class="layui-form-item">
                    <label class="layui-icon layui-icon-password" for="password"></label>
                    {{ login_form.password }}
                </div>

                <div class="layui-form-item">
                    <input type="checkbox" name="rememberMe" value="true" lay-skin="primary" title="remember password">
                </div>
                <div class="layui-form-item">
                    <button class="layui-btn layui-btn layui-btn-normal layui-btn-fluid" lay-submit=""
                            lay-filter="login">Login In
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
</body>

<script src="/static/js/jquery.min.js" charset="utf-8"></script>
<script src="/static/layui/layui.js" charset="utf-8"></script>
<script>
    layui.use(['form'], function () {
        var form = layui.form,
            layer = layui.layer;


      
        form.on('submit(login)', function (data) {
            param = data.field;
            $.post('{% url 'picture:login' %}', param, function (res) {
                if (res["status"]) {
                    layer.confirm("Login Sucessful!", {
                        btn: ['confirm'] 
                    }, function () {
                        parent.window.location.href = "{% url 'picture:image_list' %}"
                    })
                } else {
                    res = JSON.parse(res["res"]);
                    var msg_count = Object.keys(res)

                    layer.msg(res[msg_count[0]][0].message, {
                        icon: 5,
                        shift: 6
                    })
                    $(".layui-input[name='" + msg_count[0] + "']").focus()

                    $(".layui-input[name='" + msg_count[0] + "']").addClass("layui-form-danger");
                }
            });
            return false;
        });
    });
</script>

</html>

local_web/templates/upload_image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload image</title>
    <link rel="stylesheet" href="/static/layui/css/layui.css" media="all">
</head>
<body>
<div class="layui-card">
    <div class="layui-card-header">Upload image</div>
    
    <div class="layui-card-body">
        <div class="layui-upload">
            <div class="layui-upload-drag" id="uploadbtn" style="width: 94%">
                <i class="layui-icon layui-icon-upload"></i>
                <p>Drop the file here</p>
            </div>
            <div class="layui-upload-list">
                <img class="layui-upload-img" id="demo1">
                <div id="tag" style="font-size: 18px;margin-top: 10px"></div>
            </div>
        </div>
    </div>
</div>


<script src="/static/js/jquery.min.js" charset="utf-8"></script>
<script src="/static/layui/layui.js" charset="utf-8"></script>
<script>
    layui.use('upload', function () {
        var upload = layui.upload;

        var uploadInst = upload.render({
            elem: '#uploadbtn'
            , url: "{% url 'picture:upload_image' %}"
            // , before: function (obj) {
            //     
            //     obj.preview(function (index, file, result) {
            //         $('#demo1').attr('src', result);
            //     });

            // }
            , done: function (res) {
               
                //alert(JSON.stringify(res.data.src))
               
                if (res.code > 0) {
                    return layer.msg('Failed');
                }
                layer.msg('Done');
                window.location.href="/picture/image_list/"



            }
            , error: function () {
                
                var demoText = $('#demoText');
                demoText.html('<span style="color: #FF5722;">上传失败</span> <a class="layui-btn layui-btn-xs demo-reload">重试</a>');
                demoText.find('.demo-reload').on('click', function () {
                    uploadInst.upload();
                });
            }
        });
    })
</script>
</body>
</html>